# Enable this, if you want to prevent the crates from changing their surrounding blocks.
# Examples:
# If a crate spawns on a 'dirt path' block, that block will become dirt, if this feature is disabled.
# Warning: This will probably tank your performance at crate spawning, if lots of crates spawn (lots = hundreds)
# Changing this requires a restart!
listen-to-block-physics: false

# Enable this, if you want to prevent some blocks that
# replaced by crates in certain cases.
dont-replace-blocks: true

# Allows players to track the nearest spawned crate using a compass
tracker:
    enabled: true

    # Start tracking when players join, otherwise players can use /envoy link
    track-on-join: true

    # How long is the delay between distance settings (in seconds)
    notification-cooldown: 5